// <auto-generated />
using System;
using KlondaikLyubvi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlondaikLyubvi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927112853_RomanceExchangeSystem")]
    partial class RomanceExchangeSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("KlondaikLyubvi.Data.BucketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BucketItems");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.LoveNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoveNotes");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.ServiceExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequesterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceOfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ServiceOfferId");

                    b.ToTable("ServiceExchanges");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.ServiceOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrustCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Релакс",
                            Description = "Расслабляющий массаж спины и плеч",
                            Emoji = "💆‍♀️",
                            IsActive = true,
                            Name = "Массаж на 20 минут",
                            TrustCost = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Забота",
                            Description = "Вкусный завтрак и кофе, приготовленные с любовью",
                            Emoji = "🍳",
                            IsActive = true,
                            Name = "Завтрак в постель",
                            TrustCost = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Досуг",
                            Description = "Выбор фильма, плед и объятия",
                            Emoji = "🎥",
                            IsActive = true,
                            Name = "Вечер фильмов",
                            TrustCost = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Романтика",
                            Description = "Свечи, музыка и расслабление вдвоём",
                            Emoji = "🛁",
                            IsActive = true,
                            Name = "Совместная ванна",
                            TrustCost = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Забота",
                            Description = "Приготовлю твое любимое блюдо",
                            Emoji = "🍽️",
                            IsActive = true,
                            Name = "Домашний ужин",
                            TrustCost = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "Романтика",
                            Description = "Романтическая прогулка в красивом месте",
                            Emoji = "🌟",
                            IsActive = true,
                            Name = "Прогулка под звездами",
                            TrustCost = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrustCredits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Денис",
                            PasswordHash = "denis",
                            TrustCredits = 5,
                            UserName = "denis"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Лиза",
                            PasswordHash = "liza",
                            TrustCredits = 5,
                            UserName = "liza"
                        });
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaSiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.BucketItem", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.Event", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.LoveNote", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.Photo", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.ServiceExchange", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlondaikLyubvi.Data.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlondaikLyubvi.Data.ServiceOffer", "ServiceOffer")
                        .WithMany()
                        .HasForeignKey("ServiceOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Requester");

                    b.Navigation("ServiceOffer");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.ServiceOffer", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlondaikLyubvi.Data.WishlistItem", b =>
                {
                    b.HasOne("KlondaikLyubvi.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
